Devices:

  - Terranova:
      - Baudrate: 9600
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 0.2

  - Relay:
      - Baudrate: 19200
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 0.2

  - Phymotion:
      - Baudrate: 115200
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 0.5

  - Gun_Motor:
      - Baudrate: 9600
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 0.5

  - X_Motor:
      - Baudrate: 9600
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 0.5

  - Z_Motor:
      - Baudrate: 9600
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 0.5

  # Edwards Scroll pump
  - nXDS15i:
      - Baudrate: 9600
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 1

  - Gauge_Main:
      - Baudrate: 9600
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 0.5

  - Gauge_Cryo:
      - Baudrate: 9600
      - Parity: None
      - Stopbits: 1
      - Databits: 8
      - Timeout: 0.5

  - Julabo:
      - Baudrate: 4800
      - Parity: Even
      - Stopbits: 1
      - Databits: 7
      - Timeout: 0.4


Connections:
  - NOT CONNECTED:
    - Type: Not Connected

  - Moxa 1:
    - Type: Moxa-16
    - Ports:
      -  1: Terranova
      -  2: Relay
      -  3: Phymotion
      -  4: Gauge_Main
      -  6: Z_Motor
      -  7: X_Motor
      -  8: Gun_Motor
      - 10: Gauge_Cryo
      - 15: Julabo

  - Moxa 2:
    - Type: Moxa-8
    - Ports:
        - 8: nXDS15i

  - USB to RS232:
    - Type: USB
    - Ports:
      -